services:
  - type: web
    name: fastapi-app
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11 # Hoặc phiên bản Python bạn đang dùng

  - type: worker
    name: kafka-consumer
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python kafka_consumers/activity_consumer.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11 # Hoặc phiên bản Python bạn đang dùng